CREATE TABLE shirtspec_customers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    store_id INTEGER REFERENCES shirtspec_stores(id),
    customer_name TEXT NOT NULL,
    date_modified TIMESTAMP DEFAULT now() NOT NULL,
    chest INTEGER NOT NULL,
    shirt_waist INTEGER NOT NULL,
    yoke DECIMAL(4,2) NOT NULL,
    shaping INTEGER NOT NULL,
    left_sleeve DECIMAL(4,2) NOT NULL,
    right_sleeve DECIMAL(4,2) NOT NULL,
    left_cuff DECIMAL(4,2) NOT NULL,
    right_cuff DECIMAL(4,2) NOT NULL,
    tail INTEGER NOT NULL,
    collar DECIMAL(4,2) NOT NULL
);

DROP TYPE IF EXISTS shoulder_line;

CREATE TYPE shoulder_line AS ENUM (
    'regular',
    'square',
    'slope',
    'exteme-slope',
    'drop-right',
    'drop-left'
);

ALTER TABLE shirtspec_customers ADD COLUMN shoulder_line shoulder_line;